apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tuwunel.fullname" . }}-config
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
data:
  tuwunel.toml: |
    [global]
    server_name = "{{ required "serverName is required" .Values.serverName }}"
    database_path = "{{ .Values.databasePath }}"
    port = {{ .Values.port | int }}
    address = ["0.0.0.0"]
    new_user_displayname_suffix = "{{ .Values.config.newUserDisplaynameSuffix }}"
    max_request_size = {{ .Values.config.maxRequestSize }}
    allow_registration = {{ .Values.config.allowRegistration }}
    allow_federation = {{ .Values.config.allowFederation }}
    {{- if .Values.config.yesIAmVerySure }}
    yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse = true
    {{- end }}

    {{- if .Values.metrics.enabled }}
    [metrics]
    enabled = true
    bind = "0.0.0.0"
    port = {{ .Values.metrics.port | int }}
    {{- end }}
