{{- if and .Values.matrixRtc.enabled .Values.matrixRtc.authService.deploy .Values.matrixRtc.authService.ingress.enabled }}
{{- $fullName := include "tuwunel.fullname" . }}
{{- $svcPort := .Values.matrixRtc.authService.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-matrixrtc-auth
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
  {{- with .Values.matrixRtc.authService.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.matrixRtc.authService.ingress.className }}
  ingressClassName: {{ .Values.matrixRtc.authService.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.matrixRtc.authService.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.matrixRtc.authService.ingress.pathPrefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-matrixrtc-auth
                port:
                  number: {{ $svcPort }}
{{- end }}
