{{- if and .Values.matrixRtc.enabled .Values.matrixRtc.authService.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuwunel.fullname" . }}-matrixrtc-auth
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
    app.kubernetes.io/component: matrixrtc-auth
spec:
  type: {{ .Values.matrixRtc.authService.service.type }}
  ports:
    - port: {{ .Values.matrixRtc.authService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tuwunel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: matrixrtc-auth
{{- end }}
