{{- if .Values.wellKnown.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tuwunel.fullname" . }}-wellknown
  labels:
    {{- include "tuwunel.labels" . | nindent 4 }}
data:
  server.json: |
    {
      "m.server": "matrix.{{ .Values.serverName }}:443"
    }
  client.json: |
    {
      "m.homeserver": {
        "base_url": "https://matrix.{{ .Values.serverName }}"
      }{{- if and .Values.matrixRtc.enabled .Values.matrixRtc.wellKnown.enabled }},
      "org.matrix.msc4143.rtc_foci": [
        {{- range $index, $foci := .Values.matrixRtc.wellKnown.foci }}
        {{- if $index }},{{ end }}
        {
          "type": {{ $foci.type | quote }},
          "livekit_service_url": {{ $foci.livekit_service_url | quote }}
        }
        {{- end }}
      ]{{- end }}
    }
{{- end }}
